[
            (fields)
            (function)
            (data)
            (record)
            (generalize)
            (mutual)
            (abstract)
            (private)
            (instance)
            (macro)
            (postulate)
            (primitive)
            (macro)
            (module)
            (comment)
            (record_assignments)
            (field_assignments)
        ] @fold

